[add] filter of importable orders by state
OCA/connector-prestashop pull request #41
Opened 2017-04-03 08:56 UTC by simahawk

If `backend_record.importable_order_state_ids` is valued
we check if current order is in the list.
If not, the job fails gracefully.

TODO: add tests.

2017-04-03 09:09 UTC, simahawk commented
Damn, this test is still failing randomly https://travis-ci.org/OCA/connector-prestashop/jobs/217990989#L1056.
@pedrobaeza @sergio-teruel @guewen any idea on how we can make this reliable?

2017-05-11 08:41 UTC, simahawk commented
@guewen after job restart the flappy test passed here too :smile:

2017-05-18 14:34 UTC, guewen approved these changes

2017-05-18 14:46 UTC, pedrobaeza commented on connector_prestashop/models/sale_order/importer.py
> +    def _rule_state(self, record, mode):
Why are you passing payment mode?

2017-05-18 17:00 UTC, simahawk commented on connector_prestashop/models/sale_order/importer.py
> +    def _rule_state(self, record, mode):
just to respect the same signature. Not mandatory indeed, but if someone wants to customize it further based also on payment mode is feasible with it.

2017-05-18 17:05 UTC, pedrobaeza commented on connector_prestashop/models/sale_order/importer.py
> +    def _rule_state(self, record, mode):
Well, it's not the normal to need that, but it doesn't hurt.

2017-05-18 17:05 UTC, pedrobaeza requested changes
Please change module version number.

2017-05-19 06:44 UTC, simahawk commented
@pedrobaeza rebased and changed version to 1.0.4. Maybe better 1.1 since is a new feat?

2017-05-19 07:13 UTC, pedrobaeza commented
Well, technically speaking doesn't imply to update the module, but what you prefer. There's a Travis error now.

2017-05-19 07:25 UTC, simahawk commented
@pedrobaeza always the same stupid test on export qty which fails randomly... @guewen and I spent some time in trying to fix that but no luck :sob: 
I'll run the build again to see if it passes.

2017-08-21 09:57 UTC, simahawk commented
@pedrobaeza can we merge this? we are using it in prod since months...

2017-08-21 10:31 UTC, pedrobaeza approved these changes
OK, but we should fix this test ASAP. It's failing more and more and it distracts us from real errors

2017-08-21 10:32 UTC, merged

2017-08-21 10:51 UTC, simahawk commented
@pedrobaeza you are right and both me and Guewen spent time on that: no luck. Sounds like is not an easy one. Tnx for merging sir! :)