Fix path to id
OCA/connector-prestashop pull request #72
Opened 2017-08-18 12:27 UTC by guewen

'value' is a product.attribute.value, which is the type of record
expected in 'odoo_id', so there is no such thing as 'val_id'

2017-08-21 09:00 UTC, simahawk approved these changes

2017-08-21 09:00 UTC, simahawk commented
one of the test fails as usual for export qty flappy test

2017-08-21 09:01 UTC, simahawk requested changes
@guewen can you increase version number?

2017-08-21 09:41 UTC, simahawk approved these changes

2017-09-13 09:47 UTC, simahawk commented
this one has been fixed into #82

2018-08-22 07:56 UTC, pedrobaeza commented
Superseeded by #82

2018-08-22 07:56 UTC, closed without merging